server:
  port: 8762

spring:
  application:
    name: service-a
  #zipkin:
    #base-url: http://localhost:9411

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15  # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    registry-fetch-interval-seconds: 10 # 拉取服务注册信息间隔（缺省为30s）
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/,http://localhost:20002/eureka/
    healthcheck:
      enabled: true # 开启健康检查（依赖spring-boot-starter-actuator）